### ISSUE TITLE
chore: rewrite todo list

### ISSUE THREAD

**Issue by SebassNoob** [SebassNoob/annoybot#1]
- [x] migrate to SQLAlchemy as ORM
- [x] impl Alembic
- [x] init bot
- [x] split cogs into sep file per command
- [x] make public dir for constants
- [x] link to Turso
- [x] fix noob code
- [x] reimpl existing CI/CD (webhooks, versioning, git actions)
- [x] setup env on prod server aka old computer + deploy on Turso
- [x] update legal docs
- [x] write patch notes and release in #announcements
